---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by james.
--- DateTime: 8/13/2020 10:28 PM
---

function onButtonPress(nodeEntry)
    Debug.console("nodeEntry: ",nodeEntry);
    --declarations
    local nXP = 0;

    --Gather up XP from the list below.
    for _,v in pairs(DB.getChildren("partysheet.quests")) do
        if DB.getValue(v, "xpawarded", 0) == 0 then
            nXP = nXP + DB.getValue(v, "xp", 0);
            DB.setValue(v, "xpawarded", "number", 1);
        end
    end
    Debug.console("nXP: ",nXP);

    --We don't want to call awardXP if there is nothing to send.
    if nXP ~= 0 then
        awardXP(nXP);
    end
end

function awardXP(nXP)
    -- decalrations
    local aParty = {};

    -- gathers a list of characters and saves them to aParty
    for _,v in pairs(DB.getChildren("partysheet.partyinformation")) do
        local sClass, sRecord = DB.getValue(v, "link");
        if sClass == "charsheet" and sRecord then
            local nodePC = DB.findNode(sRecord);
            if nodePC then
                local sName = DB.getValue(v, "name", "");
                table.insert(aParty, { name = sName, node = nodePC } );
            end
        end
    end
    Debug.console("aParty: ",aParty);

    -- go through list of characters and place the value in "exp"
    for _,v in ipairs(aParty) do
        local nNewAmount = DB.getValue(v.node, "exp", 0) + nXP;
        DB.setValue(v.node, "exp", "number", nNewAmount);

        -- it gathers the value given for each character to display later.
        v.given = nXP;
    end

    -- Output results to chat
    local msg = {font = "msgfont"};
    msg.icon = "xp";
    for _,v in ipairs(aParty) do
        msg.text = "[" .. v.given .. " XP] -> " .. v.name;
        Comm.deliverChatMessage(msg);
    end

    msg.icon = "portrait_gm_token";
    msg.text = Interface.getString("ps_message_xpaward") .. " (" .. nXP .. ")";
    Comm.deliverChatMessage(msg);
end