---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by james.
--- DateTime: 8/13/2020 5:28 PM
---

function onValueChanged()

    local total_exp = window.exp.getValue() - window.expneeded.getValue();
    Debug.console("total_exp: ",total_exp);
    window.exp_remains.setValue(total_exp);

end